# Node.js with React and Express Build Pipeline

trigger:
  branches:
    include:
      - master

pool:
  name: Windows

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      cd react-client
      npm install
      npm run build
    displayName: 'Install and Build Frontend'

  - script: |
      npm install
    displayName: 'Install Backend Dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
      exclude: |
        node_modules/**
        frontend/node_modules/**
        frontend/build/**
      verbose: true
    displayName: 'Archive Code'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'combined'
      pathToPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    displayName: 'Publish Combined Artifact'
